CREATE TABLE properties (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  owner_id INT UNSIGNED NOT NULL,
  title VARCHAR(200) NULL,
  description TEXT NULL,
  location VARCHAR(255) NULL,
  property_type ENUM('room', 'studio', 'flat', 'apartment', 'office', 'parking') NOT NULL,
  monthly_rent DECIMAL(12,2) NULL,
  deposit_amount DECIMAL(12,2) NULL,
  currency CHAR(3) NOT NULL DEFAULT 'BDT',
  size_sqft DECIMAL(10,2) NULL,
  bedrooms SMALLINT UNSIGNED NULL,
  bathrooms SMALLINT UNSIGNED NULL,
  furnished BOOLEAN NOT NULL DEFAULT TRUE,
  bachelor_allowed BOOLEAN NOT NULL DEFAULT TRUE,
  family_allowed BOOLEAN NOT NULL DEFAULT TRUE,
  moderation_status ENUM('draft', 'pending', 'approved', 'rejected') NOT NULL DEFAULT 'draft',
  is_available BOOLEAN NOT NULL DEFAULT TRUE,
  available_from DATE NULL,
  rejection_reason TEXT NULL,
  reviewed_by INT UNSIGNED NULL,
  reviewed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_properties_owner (owner_id),
  KEY idx_properties_reviewer (reviewed_by),
  KEY idx_properties_type (property_type),
  KEY idx_properties_visibility (moderation_status, is_available, available_from),
  KEY idx_properties_rent (monthly_rent),
  KEY idx_properties_created (created_at),
  CONSTRAINT fk_properties_owner FOREIGN KEY (owner_id) REFERENCES users (id)
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_properties_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id)
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT chk_properties_type CHECK (property_type IN ('room', 'studio', 'flat', 'apartment', 'office', 'parking')),
  CONSTRAINT chk_properties_moderation CHECK (moderation_status IN ('draft', 'pending', 'approved', 'rejected')),
  CONSTRAINT chk_properties_rent CHECK (monthly_rent >= 0),
  CONSTRAINT chk_properties_deposit CHECK (deposit_amount >= 0),
  CONSTRAINT chk_properties_size CHECK (size_sqft >= 0),
  CONSTRAINT chk_properties_furnished CHECK (furnished IN (0, 1)),
  CONSTRAINT chk_properties_bachelor CHECK (bachelor_allowed IN (0, 1)),
  CONSTRAINT chk_properties_family CHECK (family_allowed IN (0, 1)),
  CONSTRAINT chk_properties_available CHECK (is_available IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
